version: '3'
services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOCKERPORT: ${DOCKERPORT}
      # For use with LetsEncrypt, see README.md
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      # For use with LetsEncrypt, see README.md
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      # For use with LetsEncrypt, see README.md
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    ports:
      - ${DOCKERPORT}:80
    links:
      - database
    volumes:
      - "./do-not-commit:/do-not-commit"
      - "uploaded-files:/var/www/html/images"
      - "./docker-resources:/docker-resources"
  elasticsearch:
    image: elasticsearch:7.17.8
    # According to
    # https://gerrit.wikimedia.org/g/mediawiki/extensions/CirrusSearch/%2B/HEAD/README
    # "Only Elasticsearch v6.8 is supported."
    # but 6.8.23 gives me: "no matching manifest for linux/arm64/v8 in the manifest list entries"
    # 7.17.8 works on mac m1, but 6.8.23 requires an intel vm.
    image: elasticsearch:7.17.8
    restart: always
    # https://hub.docker.com/_/elasticsearch
    environment:
      discovery.type: single-node
  database:
    image: mariadb
    restart: always
    volumes:
      - "mysql:/var/lib/mysql"
      - "./do-not-commit:/do-not-commit"
      - "./docker-resources:/docker-resources"
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

volumes:
  uploaded-files:
  mysql:
